name: "Ubuntu with Docker Run"
on:
  workflow_dispatch:
    inputs:
      desktop-env:
        type: choice
        description: Select desktop environment
        options:
        - xubuntu-core
        - kde-plasma
        - cinnamon
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
  SSH_J_USERNAME: ${{ secrets.SSH_J_USERNAME }}
  SSH_J_HOSTNAME: ${{ secrets.SSH_J_HOSTNAME }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
        registry: ghcr.io
        image: ghcr.io/msh128/ubuntu-docker:${{ inputs.desktop-env }}
        options: --user 1000 --device /dev/fuse --cap-add SYS_ADMIN --privileged -v /run/systemd/system:/run/systemd/system -v /bin/systemctl:/bin/systemctl -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket -v /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu -v /lib/systemd:/lib/systemd -it
        run: /usr/bin/sudo /bin/systemctl default -vvvv
        shell: /bin/bash
