name: "Run interactive session with vnc support"
permissions: write-all
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          (
            sudo DEBIAN_FRONTEND=noninteractive apt -qq remove -y --purge firefox
            sudo su - runner -c 'docker system prune -a -f && podman system prune -a -f'
            rm -rf /usr/local/lib/android
          ) > /dev/null 2>&1 &
          (
            sudo apt -qq update
            sudo apt -qq upgrade -y
            sudo DEBIAN_FRONTEND=noninteractive apt -qq install -y dbus-x11 novnc python3-websockify tigervnc-standalone-server tigervnc-xorg-extension xserver-xorg-video-dummy
          )
          ssh-keygen -t ed25519 -q -f "$HOME/.ssh/id_ed25519" -N "" && chmod 600 "$HOME/.ssh/id_ed25519"
          curl -sL -o /usr/local/bin/ttyd $(curl -s 'https://api.github.com/repos/tsl0922/ttyd/releases/latest' | jq -r '.assets[] | select(.name|contains("x86_64")).browser_download_url') && sudo chmod a+x /usr/local/bin/ttyd
          /usr/local/bin/ttyd -p 7681 -W -t titleFixed="ttyd - ${{ github.repository }}" -t fontSize=13 -t fontFamily=monospace -m 1 /bin/bash -lc 'source ~/.bashrc; /usr/bin/tmux a || /usr/bin/tmux' > /dev/null 2>&1 &
          /usr/bin/websockify -D --web=/usr/share/novnc/ 6080 localhost:5901
          sudo sed -i 's/tigervncconfig -iconic/#tigervncconfig -iconic/g' /etc/X11/Xtigervnc-session
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:7681 -R 2:127.0.0.1:6080 -R 3:127.0.0.1:5901 > /tmp/srv.us.addr 2> /dev/null &
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=5 -T -N $(hostname)@ssh-j.com -R $(hostname):7681:127.0.0.1:7681 -R $(hostname):6080:127.0.0.1:6080 -R $(hostname):5901:127.0.0.1:5901 &
          while [ $(cat /tmp/srv.us.addr | wc -l) == 0 ]; do sleep 3; done
          ntfy_msg () {
            echo "Interactive session with vnc support for ${{ github.repository }}"
            echo ""
            echo "Connect via srv.us:"
            cat /tmp/srv.us.addr
            echo ""
            echo "Connect via ssh-j.com:"
            echo "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=5 -T -N $(hostname)@ssh-j.com -L 127.0.4.2:7681:$(hostname):7681 -L 127.0.4.2:6080:$(hostname):6080 -L 127.0.4.2:5901:$(hostname):5901"
            echo ""
            echo "Start vncserver after installing desktop environment:"
            echo "/usr/bin/vncserver -geometry 1920x960 -localhost yes -alwaysshared -SecurityTypes none :1"
          }
          curl -s -d "$(ntfy_msg)" ntfy.sh/$NTFY > /dev/null 2>&1
          for a in {1..345}
            do
              echo Random GUID: $(curl -s 'https://www.uuidgenerator.net/api/guid')
              sleep 58
          done &
          while [ ! -f /tmp/poweroff ]; do sleep 3; done && echo Stop signal received && exit
        env:
          NTFY: ${{ secrets.NTFY }}
