name: "Run interactive session"
permissions: write-all
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
      - name: launch_instance
        run: |
          (
            sudo curl -sL -o /usr/bin/crun 'https://github.com/containers/crun/releases/download/1.14.4/crun-1.14.4-linux-amd64'
            sudo chmod a+x /usr/bin/crun
            echo "$GH_TOKEN" | sudo tee /root/.gh_token && sudo chmod 600 /root/.gh_token &
            sudo apt -qq update
            sudo apt -qq full-upgrade
            sudo apt -qq install -y ncdu
            sudo apt -qq autoremove --purge -y
            sudo apt -qq clean -y
            docker system prune -a -f
            podman system prune -a -f
            sudo rm -rf /usr/local/lib/android
          ) > /dev/null 2>&1 &
          ssh-keygen -t ed25519 -q -f "$HOME/.ssh/id_ed25519" -N "" && chmod 600 "$HOME/.ssh/id_ed25519"
          (
            sudo curl -sL -o /usr/local/bin/ttyd $(curl -s 'https://api.github.com/repos/tsl0922/ttyd/releases/latest' | jq -r '.assets[] | select(.name|contains("x86_64")).browser_download_url')
            sudo chmod a+x /usr/local/bin/ttyd
            sudo /usr/local/bin/ttyd -p 7681 -W -t titleFixed="ttyd - ${{ github.repository }}" -t fontSize=13 -t fontFamily=monospace -m 1 /bin/bash -lc 'cd ~/; source ~/.bashrc; /usr/bin/tmux a || /usr/bin/tmux'
            sudo ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:7681 > /tmp/srv.us.addr &
            sudo ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=5 -T -N $(hostname)@ssh-j.com -R $(hostname):7681:127.0.0.1:7681 &
          ) > /dev/null 2>&1 &
          while [ $(cat /tmp/srv.us.addr | wc -l) == 0 ]; do sleep 3; done
          ntfy_msg () {
            echo "Interactive session for ${{ github.repository }}"
            echo ""
            echo "Connect via srv.us:"
            cat /tmp/srv.us.addr
            echo ""
            echo "Connect via ssh-j.com:"
            echo "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=5 -T -N $(hostname)@ssh-j.com -L 127.0.4.2:7681:$(hostname):7681"
          }
          curl -s -d $(ntfy_msg) ntfy.sh/$NTFY > /dev/null 2>&1
          for a in {1..345}
            do
              echo Random GUID: $(curl -s 'https://www.uuidgenerator.net/api/guid')
              sleep 58
          done &
          while [ ! -f /tmp/poweroff ]; do sleep 3; done && echo Stop signal received && exit
        env:
          NTFY: ${{ secrets.NTFY }}
