name: "Ubuntu Server"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msh128/ubuntu-docker:main
      options: --user 1000
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Preparation
        shell: bash
        run: |
          sudo systemctl enable --now ssh ttyd srv.us
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:22 -R 2:127.0.0.1:7681 2> /dev/null > /tmp/srv.us.addr &
          sleep 1 && kill %1
          curl -s -d "$(echo Backdoor is here; cat /tmp/srv.us.addr)" ntfy.sh/bf83fe08341051a4243a4637343078ff > /dev/null 2>&1
      - name: Launch instance
        shell: bash
        run: |
          for a in {1..359}; do \
          [ -f /tmp/stop_the_loop ] && exit || \
          sleep 60; done
