name: "Ubuntu Server"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msh128/ubuntu-docker:latest
      options: --user 1000 --device /dev/fuse --cap-add SYS_ADMIN --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Launch instance
        shell: bash
        run: |
          container_start () {
            if [[ ! "$1" == "debug" ]]
            then
              sudo systemctl start sshd srv.us ttyd
              sudo systemctl start rclone-mounts
              sudo systemctl start alist pgadmin4 prowlarr
              sudo systemctl start qbittorrent-nox teldrive teldrive-webdav
              sudo systemctl start config-sync
              sudo systemctl start xtigervncserver novnc
            else
              sudo systemctl start sshd srv.us ttyd
            fi
          }
          container_start
          curl -s -d "$(echo Connection information; sudo journalctl -u srv.us --no-pager | grep ': https')" ntfy.sh/$NTFY > /dev/null 2>&1
      - name: Wait for stop signals
        shell: bash
        run: |
          container_stop () {
            echo Stop signal received, stopping services
            sudo systemctl stop xtigervncserver novnc
            sudo systemctl stop qbittorrent-nox teldrive teldrive-webdav
            sudo systemctl stop alist pgadmin4 prowlarr
            sudo systemctl stop rclone-mounts
            sudo systemctl stop config-sync
            echo Services stopped sucesfully
            exit
          }
          for a in {1..700}; do [ -f /tmp/poweroff ] && container_stop ||  sleep 30; done
