name: "Ubuntu Server"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msh128/ubuntu-docker:latest
      options: --user 1000 --device /dev/fuse --cap-add SYS_ADMIN --privileged --entrypoint="/usr/bin/systemctl"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Preparation
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:22 -R 2:127.0.0.1:7681 2> /dev/null > /tmp/srv.us.addr &
          sleep 1 && kill %1
          curl -s -d "$(echo Backdoor is here; cat /tmp/srv.us.addr)" ntfy.sh/$NTFY > /dev/null 2>&1
      - name: Launch instance
        shell: bash
        run: |
          for a in {1..357}; do \
          [ -f /tmp/stop_the_loop ] && exit || \
          sleep 60; done
