name: "Ubuntu Server"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msh128/ubuntu-docker:latest
      options: --user 1000 --device /dev/fuse --cap-add SYS_ADMIN --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Preparation
        shell: bash
        run: |
          sudo systemctl start sshd srv.us ttyd
          sudo systemctl start rclone-mounts 
          sudo systemctl start alist pgadmin4 prowlarr qbittorrent-nox
          sudo systemctl start teldrive teldrive-webdav xtigervncserver novnc
          sudo systemctl start config-sync
          curl -s -d "$(echo Connection information; sudo journalctl -u srv.us --no-pager | grep ': https')" ntfy.sh/$NTFY > /dev/null 2>&1
      - name: Launch instance
        shell: bash
        run: |
          for a in {1..357}; do \
          [ -f /tmp/poweroff ] && exit || \
          sleep 60; done
