name: "Backup all repo on schedule"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"
env:
  GH_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  perform_backup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone all repository
        run: |
          gh repo clone msh128/github-actions
          gh repo clone msh128/ubuntu-docker-desktop
          gh repo clone msh128/ubuntu-docker-base
          gh repo clone msh128/ubuntu-docker
          gh repo clone msh128/secrets
          gh repo clone musahi-0128/oci-runner
          gh repo clone musahi-0128/oci-docker
          gh repo clone musahi0128/cirrus-ci
          gh repo clone musahi0128/teldrive-upload.sh
          gh repo clone musahi0128/mybinder
          gh repo clone musahi0128/srv.us
          gh repo clone musahi0128/cloud-encode
          gh repo clone musahi0128/hm-holv
          gh repo clone musahi0128/NiceHash_PauseMining
          gh repo clone musahi0128/manga-downloader
          gh repo clone musahi0128/Duckstation_HM-BTN_Helper
          gh repo clone musahi0128/subscene_downloader
          gh repo clone musahi0128/autoit_ecopaper
          gh repo clone musahi0128/db_karyawan
          gh repo clone musahi0128/db_inventaris
      - name: Backup to Google Drive
        run: |
          curl https://rclone.org/install.sh | sudo bash > /dev/null 2>&1
          rclone --config=./ubuntu-docker/home/.config/rclone/rclone.conf.min sync ./ musahi0128:Projects/GitHub --stats-log-level="NOTICE" --stats=1h \
          && (echo "Backup succesfull"; exit) \
          || (echo "Something's wrong. Please check the log for more details"; exit)
