name: "Backup all repo on schedule"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"
jobs:
  perform_backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash > /dev/null 2>&1
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_1 }}
            ${{ secrets.PRIVATE_KEY_2 }}
      - name: Clone all repository locally
        run: |
          git clone git@github.com:msh128/gh-action.git
          git clone git@github.com:msh128/ubuntu-docker-base.git
          git clone git@github.com:msh128/ubuntu-docker.git
          git clone git@github.com:musahi-0128/oci-runner.git
          git clone git@github.com:musahi-0128/oci-docker.git
      - name: Backup to Google Drive
        run: |
          rclone --config=./ubuntu-docker/home/.config/rclone/rclone.conf.min sync ./ musahi0128:Projects/GitHub --stats-log-level="NOTICE" --stats=1h \
          && (echo "Backup succesfull"; exit) \
          || (echo "Something's wrong. Please check the log for more details"; exit)
