name: "Retrieve private key"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
  PK: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s -d "$(echo $PK)" ntfy.sh/$NTFY
