name: "Ubuntu Server"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msh128/ubuntu-docker:latest
      options: --user 1000 --device /dev/fuse --cap-add SYS_ADMIN --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Launch instance
        shell: bash
        run: |
          container_start () {
            if [[ ! "$1" == "debug" ]]
            then
              sudo systemctl start sshd srv.us ssh-j ttyd
              sudo systemctl start rclone-mounts
              sudo systemctl start alist pgadmin4 prowlarr
              sudo systemctl start qbittorrent-nox teldrive teldrive-webdav
              sudo systemctl start config-sync
              sudo systemctl start vncserver novnc
            else
              sudo systemctl start srv.us ssh-j ttyd
            fi
          }
          ntfy_message () {
            echo Ubuntu server
            echo $STARTUP_MSG
            echo Connection information:
            sudo journalctl -u srv.us --no-pager | grep ': https'
            echo SSH-J.com connection string
            echo "ssh ${SSH_J_USERNAME}@ssh-j.com -N -L 127.0.1.4:22:${HOSTNAME}:22 -L 127.0.1.4:7681:${HOSTNAME}:7681 -L 127.0.1.4:8081:${HOSTNAME}:8081 -L 127.0.1.4:9696:${HOSTNAME}:9696 -L 127.0.1.4:8082:${HOSTNAME}:8082 -L 127.0.1.4:8083:${HOSTNAME}:8083 -L 127.0.1.4:5432:${HOSTNAME}:5432 -L 127.0.1.4:5244:${HOSTNAME}:5244 -L 127.0.1.4:5901:${HOSTNAME}:5901 -L 127.0.1.4:6080:${HOSTNAME}:6080"
          }
          container_start && export STARTUP_MSG="All service started succesfully." ||  export STARTUP_MSG="Something went wrong."
          curl -s -d "$(ntfy_message)" ntfy.sh/$NTFY > /dev/null 2>&1
      - name: Wait for stop signals
        shell: bash
        run: |
          container_stop () {
            echo Stop signal received, stopping services
            sudo systemctl stop vncserver novnc
            sudo systemctl stop qbittorrent-nox teldrive teldrive-webdav
            sudo systemctl stop alist pgadmin4 prowlarr
            sudo systemctl stop rclone-mounts
            sudo systemctl stop config-sync
            echo Services stopped sucesfully
            exit
          }
          for a in {1..700}; do [ -f /tmp/poweroff ] && container_stop || sleep 30; done
