name: "Launch Ubuntu"
on:
  workflow_dispatch:
    inputs:
      desktop_environment:
        type: choice
        description: Select desktop environment
        options:
        - xubuntu-core
        - kde-plasma-desktop
        - cinnamon
        - ubuntu-mate-core
        - lubuntu-desktop
        - ubuntu-desktop-minimal
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
  SSH_J_USERNAME: ${{ secrets.SSH_J_USERNAME }}
  SSH_J_HOSTNAME: ${{ secrets.SSH_J_HOSTNAME }}
  GH_REPO_TOKEN: ${{ secrets.github_token }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_3 }}
      - name: Preparing instance
        run: |
          (sudo su - runner -c 'docker system prune -a -f && podman system prune -a -f'
            sudo rm -rf /usr/local/lib/android
            sudo snap remove --purge firefox) > /dev/null 2>&1
          git clone git@github.com:msh128/ubuntu-docker.git > /dev/null 2>&1 &
          setup_env_and_files () {
            (export DEBIAN_FRONTEND=noninteractive
            apt -qq update --fix-missing
            apt -qq install -y software-properties-common
            add-apt-repository ppa:apt-fast/stable
            apt -qq install -y apt-fast
            apt-fast -qq install -y \
            	aria2 curl dbus-x11 ffmpeg fuse3 htop inotify-tools jq less libchromaprint-tools libdbus-glib-1-2 \
            	mediainfo mkvtoolnix nano ncdu novnc openssh-client openssh-server parallel postgresql-client \
            	python3-pip python3-websockify qbittorrent-nox rename sudo speedtest-cli sqlite3 tigervnc-standalone-server tigervnc-xorg-extension \
            	tmux tzdata ubuntu-wallpapers unzip xfce4-terminal xserver-xorg-video-dummy
            apt-fast -qq full-upgrade -y
            case ${{ inputs.desktop_environment }} in
            	xubuntu-core|ubuntu-mate-core) apt-fast -qq install -y ${{ inputs.desktop_environment }}^;;
            	lubuntu-desktop) apt-fast -qq install -y ${{ inputs.desktop_environment }} --no-install-recommends;;
            	*) apt-fast -qq install -y ${{ inputs.desktop_environment }};;
            esac)
            pip install yt-dlp > /dev/null 2>&1 &
            (curl -s https://rclone.org/install.sh | bash) > /dev/null 2>&1
            curl -sL -o /usr/local/bin/ttyd $(curl -s 'https://api.github.com/repos/tsl0922/ttyd/releases/latest' | jq -r '.assets[] | select(.name|contains("x86_64")).browser_download_url')
            chmod a+x /usr/local/bin/ttyd
            mkdir -p /opt/teldrive
            curl -sL $(curl -s 'https://api.github.com/repos/divyam234/teldrive/releases/latest' | jq -r '.assets[] | select(.name|contains("linux-amd64")).browser_download_url') | tar xz -C /opt/teldrive teldrive
            curl -sLO $(curl -s 'https://api.github.com/repos/divyam234/rclone/releases/latest' | jq -r '.assets[] | select(.name|contains("linux-amd64.zip")).browser_download_url')
            chmod a+x /opt/teldrive/teldrive
            unzip -qq rclone-*.zip
            mv rclone-*/rclone* /opt/teldrive/
            chmod a+x /opt/teldrive/rclone
            rm -rf rclone-*
            curl -sL 'https://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64' | tar xz -C /opt
            chmod a+x /opt/Prowlarr/Prowlarr
            curl -fsSL 'https://alist.nn.ci/v3.sh' | bash -s install > /dev/null 2>&1
            mkdir -p /opt/alist/data
            mkdir -p /var/lib/pgadmin /var/log/pgadmin
            pip install pgadmin4 > /dev/null 2>&1 &
            curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash > /dev/null 2>&1 &
            curl -sLO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            dpkg -i cloudflared-linux-amd64.deb
            apt install -f
            rm cloudflared-linux-amd64.deb
            aria2c -q -c 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang=en-US'
            tar xjf firefox-*.tar.bz2 -C /opt
            ln -s /opt/firefox/firefox /usr/local/bin/firefox
            rm firefox-*.tar.bz2
            wget -q https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop -P /usr/local/share/applications
            (adduser --disabled-password --gecos '' ubuntu
            adduser ubuntu sudo
            echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers) > /dev/null 2>&1
            su - ubuntu -c 'mkdir -p /home/ubuntu/{Desktop,Documents,Music,Pictures,Videos,Downloads}
              echo '${{ inputs.desktop_environment }}' > /home/ubuntu/.desktop_environment' > /dev/null 2>&1
            chown ubuntu:ubuntu -R /var/lib/pgadmin /var/log/pgadmin /opt/alist
            (for a in autoremove purge clean; do apt -qq $a; done
            rm -rf /var/lib/apt/lists/*) > /dev/null 2>&1
          }
          sudo bash -c "$(declare -f setup_env_and_files); setup_env_and_files"
          sudo pip install pyopenssl --upgrade > /dev/null 2>&1
          sudo rclone copy ./ubuntu-docker/systemd /etc/systemd/system -L
          sudo rclone copy ./ubuntu-docker/home /home/ubuntu -L
          sudo chown ubuntu:ubuntu -R /home/ubuntu /mnt /opt/teldrive /opt/Prowlarr
          sudo chmod 600 /home/ubuntu/.ssh/*
          sudo su - ubuntu -c 'mkdir -p /mnt/{musahi0128,drive,drive1}'
          sudo sed -i 's/tigervncconfig -iconic/#tigervncconfig -iconic/g' /etc/X11/Xtigervnc-session
      - name: Launch ${{ inputs.desktop_environment }}
        run: |
          for a in ssh-j srv.us
            do
              sudo sed -i 's/127.0.0.1:8084/127.0.0.1:8085/g' /etc/systemd/system/${a}.service
          done
          launch_instance () {
            echo "$GH_REPO_TOKEN" > /home/ubuntu/.gh-repo-token && chmod 600 /home/ubuntu/.gh-repo-token && chown ubuntu:ubuntu /home/ubuntu/.gh-repo-token
            sudo systemctl daemon-reload
            sudo systemctl start sshd srv.us ssh-j cloudflared ttyd
            sudo systemctl start rclone-mounts
            sudo systemctl start config-sync
            sudo systemctl start qbittorrent-nox teldrive teldrive-webdav
            sudo systemctl start vncserver novnc
            sudo su - ubuntu -c 'cd /home/ubuntu/.filebrowser
              while [ ! -f /home/ubuntu/.filebrowser/filebrowser.db ]; do sleep 3; done
              /usr/local/bin/filebrowser config set --port=8085'
            sudo systemctl start alist pgadmin4 prowlarr
          } > /dev/null 2>&1
          ntfy_message () {
            echo Ubuntu on GitHub Action
            echo ""
            echo Connect via srv.us:
            sudo journalctl -u srv.us --no-pager | grep ': https'
            echo ""
            echo Connect via ssh-j.com:
            echo "ssh ${SSH_J_USERNAME}@ssh-j.com -N -L 127.0.4.1:22:${SSH_J_HOSTNAME}:22 -L 127.0.4.1:7681:${SSH_J_HOSTNAME}:7681 -L 127.0.4.1:8081:${SSH_J_HOSTNAME}:8081 -L 127.0.4.1:9696:${SSH_J_HOSTNAME}:9696 -L 127.0.4.1:8082:${SSH_J_HOSTNAME}:8082 -L 127.0.4.1:8083:${SSH_J_HOSTNAME}:8083 -L 127.0.4.1:5050:${SSH_J_HOSTNAME}:5050 -L 127.0.4.1:5244:${SSH_J_HOSTNAME}:5244 -L 127.0.4.1:5901:${SSH_J_HOSTNAME}:5901 -L 127.0.4.1:6080:${SSH_J_HOSTNAME}:6080 -L 127.0.4.1:8084:${SSH_J_HOSTNAME}:8084"
            echo ""
            echo Connect via cloudflared:
            cat /home/ubuntu/.cloudflared/cloudflared.addr
          }
          launch_instance && echo "All services started sucesfully." || echo "Something's wrong"
          while [ ! $(sudo systemctl is-active sshd srv.us ssh-j ttyd rclone-mounts alist pgadmin4 prowlarr qbittorrent-nox teldrive teldrive-webdav vncserver novnc | uniq | wc -l) == 1 ]; do sleep 3; done
          curl -s -d "$(ntfy_message)" ntfy.sh/$NTFY > /dev/null 2>&1
      - name: Wait for stop signals
        run: |
          for a in {1..330}; do echo "Random GUID: $(curl -s https://www.uuidgenerator.net/api/guid)" && sleep 58; done &
          while [ ! -f /tmp/poweroff ]; do sleep 3; done
          echo Stop signal received
          echo Stopping services
          stop_services () {
            sudo systemctl stop vncserver novnc
            sudo systemctl stop qbittorrent-nox teldrive teldrive-webdav
            sudo systemctl stop alist pgadmin4 prowlarr
            sudo systemctl stop config-sync
            sudo systemctl stop rclone-mounts
          }
          stop_services && echo Services stopped sucesfully || echo "Something's wrong"
          exit
