name: "Launch Ubuntu from docker images"
on:
  workflow_dispatch:
    inputs:
      desktop-env:
        type: choice
        description: Select desktop environment
        options:
        - xubuntu-core
        - kde-plasma-desktop
        - cinnamon
        - ubuntu-mate-core
        - lubuntu-desktop
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
  SSH_J_USERNAME: ${{ secrets.SSH_J_USERNAME }}
  SSH_J_HOSTNAME: ${{ secrets.SSH_J_HOSTNAME }}
  GH_REPO_TOKEN: ${{ secrets.github_token }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msh128/ubuntu-docker:${{ inputs.desktop-env }}
      options: --user 1000 --device /dev/fuse --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Launch ${{ inputs.desktop-env }}
        shell: bash
        run: |
          container_start () {
            echo "$GH_REPO_TOKEN" > /home/ubuntu/.gh-repo-token && chmod 600 /home/ubuntu/.gh-repo-token && chown 1000:1000 /home/ubuntu/.gh-repo-token
            sudo apt update
            sudo apt -qq full-upgrade -y
            sudo service dbus start
            [ -f /etc/gdm3/custom.conf ] && sed -i 's/^#.*WaylandEnable=.*/WaylandEnable=false/' /etc/gdm3/custom.conf || true
            if [[ ! "$1" == "debug" ]]
            then
              sudo systemctl start sshd srv.us ssh-j ttyd
              sudo systemctl start rclone-mounts
              sudo systemctl start config-sync
              sudo systemctl start qbittorrent-nox teldrive teldrive-webdav novnc
              /bin/bash -lc 'cd /home/ubuntu/.filebrowser
                while [ ! -f /home/ubuntu/.filebrowser/filebrowser.db ]; do sleep 3; done
                /usr/local/bin/filebrowser config set --port=8084'
              sudo systemctl start alist pgadmin4 prowlarr filebrowser
              sudo systemctl start vncserver
            else
              sudo systemctl start srv.us ssh-j ttyd
            fi
          } > /dev/null 2>&1
          ntfy_message () {
            echo Ubuntu on GitHub Action
            echo ""
            echo Connect via srv.us:
            sudo journalctl -u srv.us --no-pager | grep ': https'
            echo ""
            echo Connect via ssh-j.com:
            echo "ssh ${SSH_J_USERNAME}@ssh-j.com -N -L 127.0.4.1:22:${SSH_J_HOSTNAME}:22 -L 127.0.4.1:7681:${SSH_J_HOSTNAME}:7681 -L 127.0.4.1:8081:${SSH_J_HOSTNAME}:8081 -L 127.0.4.1:9696:${SSH_J_HOSTNAME}:9696 -L 127.0.4.1:8082:${SSH_J_HOSTNAME}:8082 -L 127.0.4.1:8083:${SSH_J_HOSTNAME}:8083 -L 127.0.4.1:5050:${SSH_J_HOSTNAME}:5050 -L 127.0.4.1:5244:${SSH_J_HOSTNAME}:5244 -L 127.0.4.1:5901:${SSH_J_HOSTNAME}:5901 -L 127.0.4.1:6080:${SSH_J_HOSTNAME}:6080 -L 127.0.4.1:8084:${SSH_J_HOSTNAME}:8084"
          }
          container_start && echo "All good." || echo "Something's wrong"
          curl -s -d "$(ntfy_message)" ntfy.sh/$NTFY > /dev/null 2>&1
      - name: Wait for stop signals
        shell: bash
        run: |
          for a in {1..345}; do echo "Random GUID: $(curl -s https://www.uuidgenerator.net/api/guid)" && sleep 58; done &
          while [ ! -f /tmp/poweroff ]; do sleep 3; done
          echo Stop signal received
          echo Stopping services
          stop_services () {
            sudo systemctl stop vncserver novnc -vvvv
            sudo systemctl stop qbittorrent-nox teldrive teldrive-webdav -vvvv
            sudo systemctl stop alist pgadmin4 prowlarr filebrowser -vvvv
            sudo systemctl stop rclone-mounts -vvvv
            sudo systemctl stop config-sync -vvvv
          }
          stop_services && echo Services stopped sucesfully || echo "Something's wrong"
          exit
