name: "Windows"
on:
  workflow_dispatch:
env:
  NTFY: ${{ secrets.NTFY }}
  SSH_J_USERNAME: ${{ secrets.SSH_J_USERNAME }}
  SSH_J_HOSTNAME: ${{ secrets.SSH_J_HOSTNAME }}
jobs:
  launch_instance:
    runs-on: windows-latest
    steps:
      - name: Setup host access
        run: |
          curl -sL -o "C:\Users\runneradmin\ttyd.exe" "https://github.com/tsl0922/ttyd/releases/download/1.7.4/ttyd.win32.exe"
          mkdir "C:\Users\runneradmin\.ssh"
          ssh-keygen -t ed25519 -q -f "C:\Users\runneradmin\.ssh\id_ed25519" -N ""
          Start-Job -ScriptBlock {
            C:\Users\runneradmin\ttyd.exe -p 7681 -W -t titleFixed="ttyd - Windows on GitHub Action" -t fontSize=13 -t fontFamily=monospace
          }
          START /B "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=NUL -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:7681 -R 2:127.0.0.1:6080 -R 3:127.0.0.1:5901"
          ping -n 21000 localhost > NUL
