name: "Windows"
on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Jakarta
  NTFY: ${{ secrets.NTFY }}
  GH_EMAIL: ${{ secrets.GH_EMAIL }}
  SSH_J_USERNAME: ${{ secrets.SSH_J_USERNAME }}
  SSH_J_HOSTNAME_ANDROID: ${{ secrets.SSH_J_HOSTNAME_ANDROID }}
  AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
  AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
jobs:
  launch_instance:
    runs-on: windows-latest
    steps:
      - name: Test
        run: |
          md C:\Users\runner\.ssh
          ssh-keygen -t ed25519 -q -f "C:\Users\runner\.ssh\id_ed25519" -N ""
          Invoke-WebRequest -Uri https://github.com/tsl0922/ttyd/releases/download/1.7.4/ttyd.win32.exe -OutFile ttyd.exe
          choco install tightvnc -y --installArguments 'SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=0 SET_ALLOWLOOPBACK=1 VALUE_OF_ALLOWLOOPBACK=1 '
          Start-Process -NoNewWindow -PassThru -FilePath .\ttyd.exe -ArgumentList "-p 7681 -W -t fontSize=13 -t fontFamily=monospace -m 1 C:\Windows\System32\cmd.exe" -RedirectStandardError .\ttyd.err.txt -RedirectStandardOutput .\ttyd.out.txt
          Start-Process -NoNewWindow -PassThru -FilePath C:\Windows\System32\OpenSSH\ssh.exe -ArgumentList "-o StrictHostKeyChecking=no -o UserKnownHostsFile=NUL -o BatchMode=yes -o ServerAliveInterval=5 -T -i C:\Users\runner\.ssh\id_ed25519 srv.us -R 1:127.0.0.1:7681 -R 2:127.0.0.1:5900" -RedirectStandardError .\srv.us.err.txt -RedirectStandardOutput .\srv.us.out.txt
          Start-Process -NoNewWindow -PassThru -FilePath C:\Windows\System32\OpenSSH\ssh.exe -ArgumentList "-o StrictHostKeyChecking=no -o UserKnownHostsFile=NUL -o BatchMode=yes -o ServerAliveInterval=5 -T -N -i C:\Users\runner\.ssh\id_ed25519 srv.us -R 2e923e6f:7681:127.0.0.1:7681 -R 2e923e6f:5901:127.0.0.1:5900"
          ping localhost -n 7
          Get-Content .\srv.us.out.txt
          for ($i = 0; $i -lt 2071; $i++) {
          	Invoke-RestMethod -Uri https://www.uuidgenerator.net/api/guid
          	Start-Sleep -Seconds 9
          }
